name = "MPFaPA"
author = "Facu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "467e73062832ff61d5ca9c76f4b01ea25bf9f6bed7dccd4fc94ab6420cfe7853"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
