name = "MPFaPA"
author = "Facu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "076be2365ea36304394f3453a12bab247d2cf07e95d76bfc79a69c1c19f45074"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
