name = "SrvFacuPato"
author = "Facu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d11cc156d29a3305b4ec4e6cbe810c9a877ef3d019132c6cc4aaa282a752658a"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
