name = "MPFaPA"
author = "Facu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7faed355fc6eee11f1aa5ffb3f0ea3ed4abe9b636f6f5a04fbed766a2dfa905f"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
