name = "SrvFacuPato"
author = "Facu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c011225029fae19374302782e88a602f9eca2099a1ca40b3efdbdc5cb071bef1"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
